### PR TITLE
novacomd: Remove webos_machine_impl_dep()

### PR DESCRIPTION
**Pull request by Herrie82**
As per removal:

https://github.com/webosose/cmake-modules-webos/commit/82f4f25baedfed2ba33c7ee707f898f18da44b19

### CODE REVIEW

**Comment by Tofee** [comment]
I'm a bit hesitant on this one: should we keep the diff with upstream minimal?
- if we want that, then we can define WEBOS_TARGET_MACHINE_IMPL in the bb recipe like we did for luna-service2, and drop all the commenting of the code
- if we don't care (OSE doesn't seem to maintain it), then we could as well remove these lines completely

What is your view on this?

**Comment by Herrie82** [comment]
> I'm a bit hesitant on this one: should we keep the diff with upstream minimal?
> 
> * if we want that, then we can define WEBOS_TARGET_MACHINE_IMPL in the bb recipe like we did for luna-service2, and drop all the commenting of the code
> * if we don't care (OSE doesn't seem to maintain it), then we could as well remove these lines completely
> 
> What is your view on this?

The host/guest is only used for Novacom on the actual PC/laptop. Not really sure how to check for the host/guest using the 1st option you mentioned. It would be good to keep it in general.

**Comment by Tofee** [comment]
> The host/guest is only used for Novacom on the actual PC/laptop. Not really sure how to check for the host/guest using the 1st option you mentioned. It would be good to keep it in general.

I mean, we're not going to build novacomd for PC/laptop using our recipes in a standard build, so like luna-service2 we can set it always to "hardware" in the bb recipe.

**Comment by Herrie82** [comment]
> > The host/guest is only used for Novacom on the actual PC/laptop. Not really sure how to check for the host/guest using the 1st option you mentioned. It would be good to keep it in general.
> 
> I mean, we're not going to build novacomd for PC/laptop using our recipes in a standard build, so like luna-service2 we can set it always to "hardware" in the bb recipe.

I know, but others might want to build it for desktop, since there is no other up-2-date source for novacom. Not really sure how to cater for that situation

**Pull request merged**
